# name: Node.js CI

on:
  push:
    branches:
      - master
  schedule:
    # 4PM, that's 12PM in GMT+8
    - cron: '0 16 * * *'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with: { version: 7 }

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm ts-node ./src/transform.ts

      - name: push to release
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./generated
          publish_branch: release # a release branch
          force_orphan: true
